use [RandomDB]
go-----------------------------------------------------------------------------

if object_id(N'Secnames', N'U') is not null
begin
    drop table [Secnames]
end
go-----------------------------------------------------------------------------

create table [Secnames]
(
    [Id] int not null identity primary key,
    [Name] nvarchar(max) not null check([Name] <> N''),
    [GenderId] int not null
);
go-----------------------------------------------------------------------------

insert into [Secnames] ([GenderId], [Name])
                values (1         , N'Alexandrovich'),
                       (1         , N'Alexeyevich'),
                       (1         , N'Anatolevich'),
                       (1         , N'Andreevich'),
                       (1         , N'Antonovich'),
                       (1         , N'Arkadievich'),
                       (1         , N'Arsenievich'),
                       (1         , N'Artemovich'),
                       (1         , N'Afanasevich'),
                       (1         , N'Bogdanovich'),
                       (1         , N'Borisovich'),
                       (1         , N'Vadimovich'),
                       (1         , N'Valentinovich'),
                       (1         , N'Valerievich'),
                       (1         , N'Vasilevich'),
                       (1         , N'Viktorovich'),
                       (1         , N'Vitalievich'),
                       (1         , N'Vladimirovich'),
                       (1         , N'Vsevolodovich'),
                       (1         , N'Vyacheslavovich'),
                       (1         , N'Gavrilovich'),
                       (1         , N'Gennadievich'),
                       (1         , N'Georgievich'),
                       (1         , N'Glebovich'),
                       (1         , N'Grigorievich'),
                       (1         , N'Davydovich'),
                       (1         , N'Danilovich'),
                       (1         , N'Denisovich'),
                       (1         , N'Dmitrievich'),
                       (1         , N'Evgenyevich'),
                       (1         , N'Egorovich'),
                       (1         , N'Emelyanovich'),
                       (1         , N'Efimovich'),
                       (1         , N'Ivanovich'),
                       (1         , N'Igorevich'),
                       (1         , N'Ilyich'),
                       (1         , N'Iosifovich'),
                       (1         , N'Kirillovich'),
                       (1         , N'Konstantinovich'),
                       (1         , N'Korneevich'),
                       (1         , N'Leonidovich'),
                       (1         , N'Lvovich'),
                       (1         , N'Makarovich'),
                       (1         , N'Maksimovich'),
                       (1         , N'Markovich'),
                       (1         , N'Matveevich'),
                       (1         , N'Mitrofanovich'),
                       (1         , N'Mikhailovich'),
                       (1         , N'Nazarovich'),
                       (1         , N'Naumovich'),
                       (1         , N'Nikolaevich'),
                       (1         , N'Olegovych'),
                       (1         , N'Pavlovich'),
                       (1         , N'Petrovich'),
                       (1         , N'Platonovich'),
                       (1         , N'Robertovich'),
                       (1         , N'Rodionovich'),
                       (1         , N'Romanovich'),
                       (1         , N'Savelievich'),
                       (1         , N'Semenovich'),
                       (1         , N'Sergeevich'),
                       (1         , N'Stanislavovich'),
                       (1         , N'Stepanovich'),
                       (1         , N'Tarasovich'),
                       (1         , N'Timofeevich'),
                       (1         , N'Tikhonovich'),
                       (1         , N'Fedorovich'),
                       (1         , N'Feliksovich'),
                       (1         , N'Filippovich'),
                       (1         , N'Eduardovich'),
                       (1         , N'Yakovlevich'),
                       (1         , N'Yaroslavovich')
go-----------------------------------------------------------------------------

insert into [Secnames] ([GenderId], [Name])
                values (2         , N'Alexandrovna'),
                       (2         , N'Alekseevna'),
                       (2         , N'Anatolievna'),
                       (2         , N'Andreevna'),
                       (2         , N'Antonovna'),
                       (2         , N'Arkadyevna'),
                       (2         , N'Arsenyevna'),
                       (2         , N'Afanasyevna'),
                       (2         , N'Bogdanovna'),
                       (2         , N'Borisovna'),
                       (2         , N'Valentinovna'),
                       (2         , N'Valerievna'),
                       (2         , N'Vasilevna'),
                       (2         , N'Victorovna'),
                       (2         , N'Vladimirovna'),
                       (2         , N'Vladislavovna'),
                       (2         , N'Vyacheslavovna'),
                       (2         , N'Gennadievna'),
                       (2         , N'Georgievna'),
                       (2         , N'Grigorievna'),
                       (2         , N'Danilovna'),
                       (2         , N'Dmitrievna'),
                       (2         , N'Evgenievna'),
                       (2         , N'Egorovna'),
                       (2         , N'Efimovna'),
                       (2         , N'Ivanovna'),
                       (2         , N'Igorevna'),
                       (2         , N'Ilyinichna'),
                       (2         , N'Iosifovna'),
                       (2         , N'Kirillovna'),
                       (2         , N'Konstantinovna'),
                       (2         , N'Leonidovna'),
                       (2         , N'Lvovna'),
                       (2         , N'Maksimovna'),
                       (2         , N'Matveevna'),
                       (2         , N'Mikhailovna'),
                       (2         , N'Nikolaevna'),
                       (2         , N'Olegovna'),
                       (2         , N'Pavlovna'),
                       (2         , N'Petrovna'),
                       (2         , N'Platonovna'),
                       (2         , N'Robertovna'),
                       (2         , N'Romanovna'),
                       (2         , N'Semyonovna'),
                       (2         , N'Sergeevna'),
                       (2         , N'Stanislavovna'),
                       (2         , N'Stepanovna'),
                       (2         , N'Tarasovna'),
                       (2         , N'Timofeevna'),
                       (2         , N'Fedorovna'),
                       (2         , N'Feluksovna'),
                       (2         , N'Filippovna'),
                       (2         , N'Eduardovna'),
                       (2         , N'Yuryevna'),
                       (2         , N'Yakovlevna'),
                       (2         , N'Yaroslavovna')
go-----------------------------------------------------------------------------